cloudmesh/sp17-i524

.travis.yml
Makefile
README.rst
paper1/S17-TS-0006/README.rst
test-papers

This adds checks for:
Second part to cloudmesh/classes#147

new:usr: add CI test for submission

---

setup

@laszewsk This just creates a 'galaxy/HID' directory. What template do you want? What submission artifacts should be given by students?
@cloudmesh/i524-sp17-ais please verify that the changes do not break the setup for papers and projects.

new:usr: update setup to support `galaxy` submissions

---

paper1/S17-IR-2022/references.bib
paper1/S17-IR-2022/report.tex

Adding more content to paper1 (S17-IR-2022).

new: dev: Adding more content to paper1 (S17-IR-2022)

---

paper1/S17-IR-2034/report.tex

new:usr: changed some details in paper1

---

test-papers

chg: dev: be able to handle dates parsed as date or datetime object by yaml

---

paper1/S17-IR-2021/report.tex

Added a small change so that i can access pull request

added small change

---

galaxy/S17-IR-2037/roles/srirsith.emacs/.travis.yml
galaxy/S17-IR-2037/roles/srirsith.emacs/README.md
galaxy/S17-IR-2037/roles/srirsith.emacs/defaults/main.yml
galaxy/S17-IR-2037/roles/srirsith.emacs/handlers/main.yml
galaxy/S17-IR-2037/roles/srirsith.emacs/meta/main.yml
galaxy/S17-IR-2037/roles/srirsith.emacs/tasks/main.yml
galaxy/S17-IR-2037/roles/srirsith.emacs/tests/inventory
galaxy/S17-IR-2037/roles/srirsith.emacs/tests/test.yml
galaxy/S17-IR-2037/roles/srirsith.emacs/vars/main.yml

new:usr S17-IR-2037 directory for galaxy assignment

new:usr S17-IR-2037 directory for galaxy assignment

---

galaxy/S17-IR-2029/README.md
galaxy/S17-IR-2029/inventory
galaxy/S17-IR-2029/playbook.yaml
galaxy/S17-IR-2029/roles/nramaraj.emacs/README.md
galaxy/S17-IR-2029/roles/nramaraj.emacs/defaults/main.yml
galaxy/S17-IR-2029/roles/nramaraj.emacs/handlers/main.yml
galaxy/S17-IR-2029/roles/nramaraj.emacs/meta/main.yml
galaxy/S17-IR-2029/roles/nramaraj.emacs/tasks/main.yml
galaxy/S17-IR-2029/roles/nramaraj.emacs/tests/inventory
galaxy/S17-IR-2029/roles/nramaraj.emacs/tests/test.yml
galaxy/S17-IR-2029/roles/nramaraj.emacs/vars/main.yml

Pull request for ansible galaxy assignment

new:usr:ansible emacs assignment

---

galaxy/S17-IR-2031/README.md
galaxy/S17-IR-2031/ansible.cfg
galaxy/S17-IR-2031/hosts
galaxy/S17-IR-2031/playbook.yml
galaxy/S17-IR-2031/roles/emacs.backfolder/tasks/main.yml
galaxy/S17-IR-2031/roles/emacs/.travis.yml
galaxy/S17-IR-2031/roles/emacs/README.md
galaxy/S17-IR-2031/roles/emacs/defaults/main.yml
galaxy/S17-IR-2031/roles/emacs/handlers/main.yml
galaxy/S17-IR-2031/roles/emacs/meta/back-main.yml
galaxy/S17-IR-2031/roles/emacs/meta/main.yml
galaxy/S17-IR-2031/roles/emacs/tasks/main.yml
galaxy/S17-IR-2031/roles/emacs/tests/inventory
galaxy/S17-IR-2031/roles/emacs/tests/test.yml
galaxy/S17-IR-2031/roles/emacs/vars/main.yml

The target server is a vagrant box. where I am installing emacs

new: usr: added ansible galaxy code for installing emacs in target server

---

galaxy/S17-IR-2030/roles/inventory
galaxy/S17-IR-2030/roles/sowmya.emacs/.travis.yml
galaxy/S17-IR-2030/roles/sowmya.emacs/README.md
galaxy/S17-IR-2030/roles/sowmya.emacs/defaults/main.yml
galaxy/S17-IR-2030/roles/sowmya.emacs/handlers/main.yml
galaxy/S17-IR-2030/roles/sowmya.emacs/meta/main.yml
galaxy/S17-IR-2030/roles/sowmya.emacs/tasks/main.yml
galaxy/S17-IR-2030/roles/sowmya.emacs/tests/inventory
galaxy/S17-IR-2030/roles/sowmya.emacs/tests/test.yml
galaxy/S17-IR-2030/roles/sowmya.emacs/vars/main.yml
galaxy/S17-IR-2030/roles/test.yml

new:usr Installed emacs in the remote machine

new:usr Installed emacs in the remote machine

---

paper1/S17-IR-2004/report-review.tex

paper review for S17-IR-2004

---

paper1/S17-IO-3017/Makefile
paper1/S17-IO-3017/index.rst
paper1/S17-IO-3017/styles/IEEEtran.bst
paper1/S17-IO-3017/styles/ao.sty
paper1/S17-IO-3017/styles/aop.sty
paper1/S17-IO-3017/styles/auto/i524.el
paper1/S17-IO-3017/styles/i523.sty
paper1/S17-IO-3017/styles/i524.sty
paper1/S17-IO-3017/styles/josaa.sty
paper1/S17-IO-3017/styles/josab.sty
paper1/S17-IO-3017/styles/ol.sty
paper1/S17-IO-3017/styles/osajnl-orig.bst
paper1/S17-IO-3017/styles/osajnl.bst
paper1/S17-IO-3017/styles/osajnl.cls
paper1/S17-IO-3017/styles/osajnlnt.bst
project/S17-IO-3017/report/report.tex

S17-IO-3017. Adding files to remove error in compiling.

new:dev: adding files to remove error in compiling

---

paper2/S17-IO-3010/README.rst
project/S17-IO-3010/README.rst

My second intermediate push for paper2.  Expect final draft later this evening.

usr:chg: updated paper2 and project READMEs

---

paper2/S17-IR-2021/report.tex

new: usr:improve url: submission of paper2 HID S17-IR-2021

new: usr:improve url: submission of paper2 HID S17-IR-2021

---

paper1/S17-IR-2022/report.tex

Updated the URL for paper1 as per professor's instructions on Piazza.

fix:usr: Updated the URL for paper1

---

paper1/S17-IR-2021/report.tex

fix :usr : fixed the paper link and corrected some references

fix :usr : fixed the paper link and corrected some references

---

project/S17-IR-P001/Installation/Instructions.txt

:new:usr added Installation folder containing instructions for ansible deployment

:new:usr added Installation folder containing instructions

---

project/S17-IR-P013/code/weather_data_analysis/src/iu/i524/S17IRP013/dao/hbase_connect.py
project/S17-IR-P013/code/weather_data_analysis/src/iu/i524/S17IRP013/dao/stations_dao.py
project/S17-IR-P013/code/weather_data_analysis/src/iu/i524/S17IRP013/dao/weather_dao.py
project/S17-IR-P013/code/weather_data_analysis/src/iu/i524/S17IRP013/data/data_service.py
project/S17-IR-P013/code/weather_data_analysis/src/iu/i524/S17IRP013/ncdc/weather_services.py
project/S17-IR-P013/code/weather_data_analysis/src/iu/i524/S17IRP013/test/TestRunner.py
project/S17-IR-P013/code/weather_data_analysis/src/iu/i524/S17IRP013/util/app_util.py

Data Curation part is complete. It requires apache thrift and happybase to connect to apache hbase table. Need few more fixes but next step is to deploy it on jetstream.

Project: Weather Data Analysis 

---

project/S17-IR-P001/README.MD
project/S17-IR-P001/code/ansible/ansible-node/tasks/main.yml
project/S17-IR-P001/code/ansible/ansible-vis/README.md
project/S17-IR-P001/code/ansible/ansible-vis/defaults/main.yml
project/S17-IR-P001/code/ansible/ansible-vis/meta/main.yml
project/S17-IR-P001/code/ansible/ansible-vis/tasks/main.yml
project/S17-IR-P001/code/ansible/ansible-vis/tests/inventory
project/S17-IR-P001/code/ansible/ansible-vis/tests/test.yml

chg: usr: modified ansible-node role to python script

chg: usr: modified ansible-node role to python script

---

project/S17-IR-P001/README.MD

chg: usr: updated README.MD

---

project/S17-IR-P001/report/report.tex

chg: usr: modified the report as per the review

chg: usr: modified the report as per the review

---

project/S17-IR-2013/code/pig/outbrain_pig

I happen to notice only now. I appologise for the confusion

chg:usr: Updated file; old file was wrongly committed earlier
